
version: '3.1'

networks:
  rede_app:    
    driver: bridge

services:

  app01: &app
    image: shenkimaro/php8.3-postgres
    hostname: app01
    networks:
      rede_app:
        aliases:
          - app01
    environment:
      - DB_HOSTNAME=db
      - PORT=9000
    depends_on:
      - db
    volumes:
      - type: bind
        source: /var/www/rinha/
        target: /var/www/html/
    deploy:
     resources:
       limits:
         cpus: '0.35'
         memory: '150MB'  

  app02:
    <<: *app
    hostname: app02    

  nginx:
    image: nginx
    restart: always
    networks:
      - rede_app
    ports:
      - 9999:80 
    depends_on:
      - app01
      - app02  
    deploy:
     resources:
       limits:
         cpus: "0.3"
         memory: "50MB"  
    volumes:
      - type: bind
        source: /var/www/rinha/container/nginx/
        target: /etc/nginx/conf.d/  

  db:
    image: postgres
    restart: always
    hostname: db
    networks:
      rede_app:
        aliases:
          - db
    environment:
      POSTGRES_PASSWORD: teste
    ports:
      - 5432:5432  
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"  
    volumes: 
      - rinha:/var/lib/postgresql/datas
      - ./container/script.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0
volumes:
  rinha: