
version: '3.1'

networks:
  rede_app:    
    driver: bridge

services:

  app01: &app
    image: php:8.3-fpm-alpine3.19
    hostname: app01
    networks:
      rede_app:
        aliases:
          - app01
    environment:
      - DB_HOSTNAME=db
      - PORT=9000
    # depends_on:
    #   - db
    volumes:
      - type: bind
        source: /var/www/git/rinha/
        target: /var/www/html/
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '0.35'
    #      memory: '150MB'  

  app02:
    <<: *app
    hostname: app02    

  nginx:
    image: nginx
    restart: always
    networks:
      - rede_app
    ports:
      - 9005:8080 
    depends_on:
      - app01
      - app02  
   # deploy:
   #   resources:
   #     limits:
   #       cpus: "0.3"
   #       memory: "50MB"  
    volumes:
      - type: bind
        source: /var/www/git/rinha/nginx/default.conf
        target: /etc/nginx/nginx.conf:ro
        #target: /etc/nginx/conf.d/  


#   db:
#     image: postgres
#     restart: always
#     hostname: db
#     environment:
#       POSTGRES_PASSWORD: teste
#     ports:
#       - 5432:5432  
#     deploy:
#       resources:
#         limits:
#           cpus: "0.5"
#           memory: "200MB"  
#     volumes: 
#       - rinha:/var/lib/postgresql/data
# volumes:
#   rinha: